source 'https://github.com/CocoaPods/Specs.git'

target 'SimpleLogin', :exclusive => true do
  pod "CleverSDK", :path => "../../"
end

target 'Tests', :exclusive => true do
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
