source 'https://github.com/CocoaPods/Specs.git'

target 'SimpleLogin' do
  platform :ios, '8.0'

  pod "CleverSDK", :path => "../../"
end

target 'Tests' do
  platform :ios, '8.0'

  use_frameworks!
  pod "CleverSDK", :path => "../../"

  pod 'Specta'
  pod 'Expecta'
end
